# Generated by Django 3.1.1 on 2020-10-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
